### ISSUE TITLE
I think the object you are referencing may be storms

### ISSUE THREAD

**Issue by gaberunte** [rammysalem/issues-lab#2]
I think that the object 'storms' from the dplyr:: package might be what you are looking for. A simple missing 's' should do the trick! 

https://github.com/rammysalem/issues-lab/blob/a078c45d3129a6b201987a3811d5da641452dc52/got_issues.Rmd#L18

**Comment by rammysalem** [comment]
Hi Gabe, thanks for pointing that out!
